apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f dc-example.yml -o nubemanifests.yml
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend-tcp
      name: frontend-tcp
    spec:
      ports:
        - name: "80"
          port: 80
          targetPort: 80
      selector:
        io.kompose.service: frontend
      type: LoadBalancer
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f dc-example.yml -o nubemanifests.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-master
      name: redis-master
    spec:
      ports:
        - name: "6379"
          port: 6379
          targetPort: 6379
      selector:
        io.kompose.service: redis-master
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f dc-example.yml -o nubemanifests.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-slave
      name: redis-slave
    spec:
      ports:
        - name: "6379"
          port: 6379
          targetPort: 6379
      selector:
        io.kompose.service: redis-slave
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f dc-example.yml -o nubemanifests.yml
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
      name: frontend
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: frontend
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f dc-example.yml -o nubemanifests.yml
            kompose.service.type: LoadBalancer
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: frontend
        spec:
          containers:
            - env:
                - name: GET_HOSTS_FROM
                  value: dns
              image: gcr.io/google-samples/gb-frontend:v4
              name: frontend
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f dc-example.yml -o nubemanifests.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-master
      name: redis-master
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: redis-master
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f dc-example.yml -o nubemanifests.yml
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: redis-master
        spec:
          containers:
            - image: k8s.gcr.io/redis:e2e
              name: redis-master
              ports:
                - containerPort: 6379
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f dc-example.yml -o nubemanifests.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-slave
      name: redis-slave
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: redis-slave
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f dc-example.yml -o nubemanifests.yml
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: redis-slave
        spec:
          containers:
            - env:
                - name: GET_HOSTS_FROM
                  value: dns
              image: gcr.io/google_samples/gb-redisslave:v3
              name: redis-slave
              ports:
                - containerPort: 6379
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}
