apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: validator
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: validator
      repository: "183708075063.dkr.ecr.us-east-1.amazonaws.com/validator"
      version: 0.1.0
#      pullSecretRef:
#        name: oci-creds
#        namespace: default
#       url: "oci://localhost:5000/helm-charts/wordpress:9.3.19"
    namespace: crossplane-system
#   insecureSkipTLSVerify: true
#   skipCreateNamespace: true
#   wait: true
#   skipCRDs: true
    values:
      service:
        type: ClusterIP
    set:
      - name: param1
        value: value2
#   valuesFrom:
#     - configMapKeyRef:
#         key: values.yaml
#         name: default-vals
#         namespace: wordpress
#         optional: false
#     - secretKeyRef:
#         key: svalues.yaml
#         name: svals
#         namespace: wordpress
#         optional: false
#  connectionDetails:
#    - apiVersion: v1
#      kind: Service
#      name: wordpress-example
#      namespace: wordpress
#      fieldPath: spec.clusterIP
#      #fieldPath: status.loadBalancer.ingress[0].ip
#      toConnectionSecretKey: ip
#    - apiVersion: v1
#      kind: Service
#      name: wordpress-example
#      namespace: wordpress
#      fieldPath: spec.ports[0].port
#      toConnectionSecretKey: port
#    - apiVersion: v1
#      kind: Secret
#      name: wordpress-example
#      namespace: wordpress
#      fieldPath: data.wordpress-password
#      toConnectionSecretKey: password
#  writeConnectionSecretToRef:
#    name: wordpress-credentials
#    namespace: crossplane-system
  providerConfigRef:
#   name: sgk8s1-helm-provider
